Test with failing unit tests

diff --git a/.github/workflows/actions_practice.yml b/.github/workflows/actions_practice.yml
--- a/.github/workflows/actions_practice.yml
+++ b/.github/workflows/actions_practice.yml
@@ -53,9 +53,10 @@ jobs: # Jobs consist different of different steps to test/simulate something. If
       - name: "Testing failed!"
         run: echo "Unit test failed"
 
-  test-condition-success:
+  prevent-push-if-failure:
     runs-on: ubuntu-latest
-    if: ${{ secrets.SUCCESS == 'success'  }}
-    steps:
-      - name:
-        run: echo "SUCCESS is 'success'"
+    needs: [test-condition-check-failure]
+    if: ${{ github.event_name == 'push' && needs.test-condition-check-failure.result == 'success' }}
+    steps: 
+      - name: Cancel workflow
+        run: echo "Unit tests failed, cancelling the workflow" && exit 1
